name: Grofast CI

on:
  push:
    branches: 
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456789
          POSTGRES_DB: mydjango
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DEBUG: 0
      EMAIL_BACKEND: "django.core.mail.backends.console.EmailBackend"
      SECRET_KEY: django-insecure-g(npd83pyofjxz+@my(sfdgs&88$^)l@$ilr)yj_ivl5*iaglm
      ENGINE: django.db.backends.postgresql
      DB_NAME: mydjango
      DB_USER: postgres
      DB_PASSWORD: 123456789
      DB_HOST: postgresql://neondb_owner:npg_DI0em8VgWtkC@ep-bold-sky-ad99gtuv-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      DB_PORT: 5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r grofast/requirements.txt
 
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
      #Update to the serverusing SSH
    #- name: Deploy to server
     # uses: webfactory/ssh-agent@v0.5.3
     # with:
      #  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
